### ISSUE TITLE
Thaumcraft-1.7.10-4.2.3.5  WITH MyTown2-1.7.10-0.0.1b

### ISSUE THREAD

**Issue by EverNife** [MyEssentials/MyTown2-Protections#63] opened 2015-04-14 00:50 UTC
-->The Arcane Bore
Actually the Wand Focus: Excavation is protected, but in the ARCANRE BORE it bypass the protection.
-->Portable Hole

I think its only this on thaumcraft

**Comment by krwminer** [comment] 2015-04-14 17:27
Duplicate of Issue #16.

**Closed as completed by krwminer** 2015-04-14 17:27 UTC
