### ISSUE TITLE
AE2 Cables/ Terminals

### ISSUE THREAD

**Issue by yepidoodles** [MyEssentials/MyTown2-Protections#74] opened 2015-04-27 15:52 UTC
AE2 Cables/ Terminals can still be wrenched off by any wrench in any mod.

**Comment by yepidoodles** [comment] 2015-04-27 16:05
As an incentive - I'll donate $50 to the person who fixes this if they fix it before the 12th May - That is when I release my server's official version of 1.7.10.

**Comment by krwminer** [comment] 2015-04-28 00:38
Please name the wrenches that can do this. The wrenches tend to change other blocks too and I want to stop them from doing that, so I usually protect against the wrenches.

**Comment by krwminer** [comment] 2015-04-28 00:39
The AE2 quartz wrench should be protected against. Let me know if that is one of them.

**Comment by yepidoodles** [comment] 2015-04-28 15:49
The AE2 quartz wrenches can still wrench off cables and terminals,

Both Quartz Wrenches from AE2
Crescent hammer from TE
BattleWrench from TE
Wrench from Forestry
Yeta Wrench from EnderIO
Precsion Sledgehammer from MFR

To the looks of it, it's not what you have protected but how it is coded: Nothing else (that I've found so far) can be wrenched off except from the cables and terminals from AE2.

**Comment by MuresanSergiu** [comment] 2015-04-28 15:51
That is correct. It has something to do with AE2 mainly, I am looking for a possible fix right now.

**Comment by yepidoodles** [comment] 2015-05-04 11:31
I was very serious about that $50 :P I need this protection

**Comment by MuresanSergiu** [comment] 2015-05-04 12:37
Don't worry, me and @krwminer are working on it. The issue is that we need to change the AE2 code itself and only then it will get fixed.

**Comment by krwminer** [comment] 2015-05-04 14:49
I have been looking at this. I have a patch for the Wrench part of the issue and I am still looking into an issue where you can bypass placing items in AE2. Both will be fixes for AE2. I hope to be able to spend a bunch more time on this on Tuesday.

**Comment by yepidoodles** [comment] 2015-05-04 19:47
Wonderful, thank you for the update ^.^

**Comment by krwminer** [comment] 2015-05-05 23:45
I submitted a PR for AE2 to fix the problem:

https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/1396

That is all I can do at this point.

**Comment by MuresanSergiu** [comment] 2015-05-12 12:57
From what it looks like, they are not gonna implement our changes into the mod anytime soon.
A way of going around this would be to use @krwminer AE2 version (only for the server), and that will fix most protection issues with AE2.

**Comment by krwminer** [comment] 2015-05-16 22:16
Closing this issue. Information is now in Issue #13.

**Closed as completed by krwminer** 2015-05-16 22:16 UTC
Labels: code-related
